Add docker-compose configuring Kafka and MongoDB
This commit adds a docker-compose.yml file that setups the containers to
run a Kafka instance and a MongoDB consumer.It is not production ready.

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -4,88 +4,105 @@ services:
   zookeeper-1:
     image: confluentinc/cp-zookeeper:latest
     ports:
-      - "12181:12181"
+      - "2181:2181"
     environment:
       ZOOKEEPER_SERVER_ID: 1
-      ZOOKEEPER_CLIENT_PORT: 12181
+      ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
       ZOOKEEPER_INIT_LIMIT: 5
       ZOOKEEPER_SYNC_LIMIT: 2
-      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888; zookeeper-2:22888:23888; zookeeper-3:32888:33888
-
-  zookeeper-2:
-    image: confluentinc/cp-zookeeper:latest
-    ports:
-      - "22181:22181"
-    environment:
-      ZOOKEEPER_SERVER_ID: 2
-      ZOOKEEPER_CLIENT_PORT: 22181
-      ZOOKEEPER_TICK_TIME: 2000
-      ZOOKEEPER_INIT_LIMIT: 5
-      ZOOKEEPER_SYNC_LIMIT: 2
-      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888; zookeeper-2:22888:23888; zookeeper-3:32888:33888
-
-  zookeeper-3:
-    image: confluentinc/cp-zookeeper:latest
-    ports:
-      - "32181:32181"
-    environment:
-      ZOOKEEPER_SERVER_ID: 3
-      ZOOKEEPER_CLIENT_PORT: 32181
-      ZOOKEEPER_TICK_TIME: 2000
-      ZOOKEEPER_INIT_LIMIT: 5
-      ZOOKEEPER_SYNC_LIMIT: 2
-      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888; zookeeper-2:22888:23888; zookeeper-3:32888:33888
+      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888
 
   kafka-1:
     image: confluentinc/cp-kafka:latest
-    ports:
-      - "19092:19092"
     depends_on:
       - zookeeper-1
-      - zookeeper-2
-      - zookeeper-3
+    ports:
+      - "9092:9092"
     environment:
       KAFKA_BROKER_ID: 1
-      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
+      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
+      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
+      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
-  kafka-2:
-    image: confluentinc/cp-kafka:latest
-    ports:
-      - "29092:29092"
+  kafka-connect:
+    image: confluentinc/cp-kafka-connect-base:latest
     depends_on:
-      - zookeeper-1
-      - zookeeper-2
-      - zookeeper-3
-    environment:
-      KAFKA_BROKER_ID: 2
-      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
-
-  kafka-3:
-    image: confluentinc/cp-kafka:latest
+      - kafka-1
     ports:
-      - "39092:39092"
-    depends_on:
-      - zookeeper-1
-      - zookeeper-2
-      - zookeeper-3
+      - "8083:8083"
     environment:
-      KAFKA_BROKER_ID: 3
-      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
+      CONNECT_BOOTSTRAP_SERVERS: "kafka-1:9092"
+      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
+      CONNECT_GROUP_ID: connect-cluster-group
+      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
+      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
+      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
+      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
+      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
+      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
+      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
+      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
+    command:
+      - bash
+      - -c
+      - |
+        #
+        echo "Installing connector plugins"
+        while : ; do
+          confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.9.1
+          if [ $? -eq 0 ] ; then
+            break
+          fi
+          echo "Installing connector plugins failed, trying again" 
+          sleep 5 
+        done    
+        #
+        echo "Launching Kafka Connect worker"
+        /etc/confluent/docker/run & 
+        #
+        echo "Waiting for Kafka Connect to start listening on localhost"
+        while : ; do
+          curl_status=$$(curl -s -o /dev/null -w %{http_code} http://localhost:8083/connectors)
+          echo -e $$(date) " Kafka Connect listener HTTP state: " $$curl_status " (waiting for 200)"
+          if [ $$curl_status -eq 200 ] ; then
+            break
+          fi
+          sleep 5 
+        done
+        #
+        echo -e "Creating connector..."        
+        curl -X POST -H "Content-Type: application/json" http://kafka-connect:8083/connectors --data '
+          {
+            "name": "mongo-sink",
+            "config": {
+              "connector.class"                : "com.mongodb.kafka.connect.MongoSinkConnector",
+              "connection.uri"                 : "mongodb://user:password@mongo:27017/hotelsearches_db",
+              "database"                       : "hotelsearches_db",
+              "collection"                     : "hotel_availability_searches",
+              "topics"                         : "hotel_availability_searches",
+              "value.converter"                : "org.apache.kafka.connect.json.JsonConverter",
+              "value.converter.schemas.enable" : "false"
+            }
+          }'
+        sleep infinity
 
-  mongodb:
-    image: mongo:latest
-    environment:
-      - MONGO_DATA_DIR=/data/db
-      - MONGO_LOG_DIR=/dev/null
-      - MONGODB_USER=test
-      - MONGODB_DATABASE=test_db
-      - MONGODB_PASS=bigdata_test
+  mongo:
+    image: docker.io/bitnami/mongodb:6.0
+    depends_on:
+      - kafka-1
+      - kafka-connect
+    restart: always
+    ports:
+      - "27017:27017"
     volumes:
-      - ./data/db:/data/db
-    ports:
-      - 27017:27017
-    command: mongod --logpath=/dev/null
+      - ./mongo-volume:/data/db
+    environment:
+      MONGODB_ADVERTISED_HOSTNAME: mongo
+      MONGODB_USERNAME: user
+      MONGODB_PASSWORD: password
+      MONGODB_DATABASE: hotelsearches_db
+      MONGODB_REPLICA_SET_MODE: primary
+      MONGODB_REPLICA_SET_NAME: rs0
+      MONGODB_ROOT_PASSWORD: root
+      MONGODB_REPLICA_SET_KEY: replicasetkey
